Vagrant.configure("2") do |config|
  config.vm.provider "docker"
  config.vm.box = "tknerr/baseimage-ubuntu-14.04"
  config.vm.box_version = "1.0.0"
  config.vm.define "vm-test2" do |instance|

  end
end
