apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  MYSQL_ROOT_PASSWORD: "123456"
  MYSQL_DATABASE: "empresa"
  MYSQL_PASSWORD: "123456"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: sistema-noticias-config
data:
  HOST_DB: db-noticias-svc:3306
  USER_DB: root


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-config
data:
  IP_SISTEMA: http://192.168.49.2:30011
