apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imagens-pvc
spec:
  resources:
    requests:
      storage: 1Gi      
  accessModes:
    - ReadWriteOnce
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sessoes-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
