/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.stdioh.testes;

import br.com.stdioh.testes.model.User;
import org.apache.commons.lang3.StringUtils;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.IntStream;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;


public class UserTest {

    private List<User> users = new ArrayList<>();
    private Integer beforeEach = 0;

    @BeforeEach
    public void populateUsers() {
        beforeEach+=1;
        System.out.println(String.format("populateUsers: %d", beforeEach));
        users = new ArrayList<>();
        IntStream.range(1, 5).forEach(value -> {
            var randStr = org.apache.commons.lang3.RandomStringUtils.random(10);
            users.add(
                    User.builder().name(randStr).email(randStr + "@email.com").build());
        });
    }


    @Test
    public void nameOfUsershouldHaveThreeLetterOrMore() {
        var tmpUser = users.get(0);
        String newName = "John";
        tmpUser.setName(newName);
        assertEquals(newName, tmpUser.getName());
    }

    @Test
    public void allUsersShouldHaveId() {

        users.forEach(user -> {
            assertTrue(user.getId() != null && !user.getId().isEmpty());
        });
    }
}
