$script1 = <<-SCRIPT
  echo Hello from a script
  echo end of hellooooo.
  echo end of hellooooo.
  echo end of hellooooo.
  echo end of hellooooo.
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.provider "vmware_desktop"
  config.vm.box = "hashicorp/bionic64"
  config.vm.network  "forwarded_port", guest: 80, host:8080
  config.vm.network "private_network", ip: "192.168.50.4"  
  #config.vm.network "private_network", type: "dhcp"
  # config.vm.network "public_network", ip: "192.168.0.33"
  # config.vm.provision :shell, path: "init.sh" 
  config.vm.provision "shell", inline: "apt update"
  config.vm.provision "shell", inline: "apt install -y puppet"
  
  config.vm.provision "shell", inline: $script1, run: 'always'
  
   # config.vm.provision "shell", inline: <<-EOF
  # "echo Hello World line 1"
  # "echo Hello World line 2"
  # EOF
  config.vm.define "vm-test1" do |instance|
    instance.vm.hostname = "vm-test1"
    instance.vm.provider :virtualbox do |vb|
      vb.name = "vm-test1"    
    end
  end
  config.vm.synced_folder "/tmp", "/trash"
  # config.vm-synced_folder ".", "/vagrant", disabled: true
 end
