/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.stdioh.javaio;

import java.io.*;

public class TesteEscrita {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {

        FileOutputStream fos = new FileOutputStream("app/testout.txt", true);
        OutputStreamWriter osw = new OutputStreamWriter(fos);
        BufferedWriter bw = new BufferedWriter(osw);
        bw.write("\nTEST");
        bw.close();

    }
}

