/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.stdioh.javaio;

import java.io.FileInputStream;
import java.io.IOException;
import java.util.Scanner;

public class TesteLeitura2 {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        try (Scanner scn = new Scanner(new FileInputStream("app/contas.csv"))) {
            while (scn.hasNextLine()) {
                System.out.println(scn.nextLine());
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }


    }
}

