/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.stdioh.javaio;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;

public class TesteLeitura {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        FileInputStream fileInputStream = new FileInputStream("app/lorem.txt");
        InputStreamReader inputStreamReader = new InputStreamReader(fileInputStream);
        BufferedReader bfr = new BufferedReader(inputStreamReader);
        bfr.lines().forEach(s -> {
            System.out.println(s);

        });

        bfr.close();

    }
}

