/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.stdioh.javaio;

import java.io.IOException;
import java.io.PrintStream;

public class TesteEscrita2 {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        try (PrintStream ps = new PrintStream("app/lorem3.txt")) {
            ps.println("123");
            ps.println("abc");
            ps.println("456");
            ps.print("def");
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println("Unable to write");
        }

//        BufferedWriter bw = new BufferedWriter(new FileWriter("app/lorem2.txt"));
//        bw.write("abc");
//        bw.write("123");
//        bw.newLine();
//        bw.write("dsalfmdasld");
//        bw.close();
//        FileOutputStream fos = new FileOutputStream("app/testout.txt", true);
//        OutputStreamWriter osw = new OutputStreamWriter(fos);
//        BufferedWriter bw = new BufferedWriter(osw);
//        bw.write("\nTEST");
//        bw.close();

    }
}

