version: "3.3"
services:
  node1:
    image: node
    container_name: node1

    volumes: 
      - ./node:/app
    working_dir: /app
    command: node index.js
    networks: 
      - my-net
    
  node2:
    image: node
    container_name: node2

    volumes: 
      - ./node:/app
    working_dir: /app
    command: node index.js
    networks: 
      - my-net
  nginx:
    image: nginx
    container_name: nginx
    networks: 
      - my-net
    volumes: 
      - "./conf.d:/etc/nginx/conf.d/"
    ports: 
      - "8787:80"
    
      
networks: 
  my-net:
    driver: bridge
