/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.stdioh321;

import br.com.stdioh321.imposto.CalculadoraImposto;
import br.com.stdioh321.imposto.ICMS;
import br.com.stdioh321.imposto.ISS;
import br.com.stdioh321.modelo.Orcamento;
import org.checkerframework.checker.units.qual.C;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.time.temporal.TemporalAccessor;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        String myDate = String.format("%d-%02d-%02d", LocalDateTime.now().getYear(), LocalDateTime.now().getMonthValue(), LocalDateTime.now().getDayOfMonth());
        var instant = Instant.now();
        System.out.println(myDate);
        System.out.println(instant.toEpochMilli());
        LocalDateTime ldt = LocalDateTime.ofInstant(instant, ZoneOffset.UTC);
        System.out.println(ldt);

    }
}
