#apiVersion: v1
#kind: Pod
#metadata:
#  name: pod-2
#  labels:
#    app: pod-2
#spec:
#  containers:
#  - name: pod-2-container
#    image: nginx
#    ports:
#      - containerPort: 80

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-2-depl
spec:
  selector:
    matchLabels:
      app: pod-2
  replicas: 2
  template:
    metadata:
      labels:
        app: pod-2
    spec:
      containers:
      - name: pod-2-container
        image: nginx
        ports:
        - containerPort: 80



---

apiVersion: v1
kind: Service
metadata:
  name: pod-2-service
spec:
  selector:
    app: pod-2
  type: NodePort
  ports:
  - port: 80
    