apiVersion: v1
kind: Pod
metadata:
  name: db-noticias-pod
  labels:
    app: db-noticias
spec:
  nodeSelector:
    node: node1
  containers:
  - name: db-noticias-container
    image: aluracursos/mysql-db:1
    envFrom:
      - configMapRef:
          name: db-config  
    ports:
      - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: db-noticias-svc
spec:
  selector:
    app: db-noticias
  ports:
  - port: 3306
  