apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
      - name: mynginx-container
        image: nginx:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: mynginx-svc
spec:
  selector:
    app: mynginx
  type: NodePort
  ports:
  - port: 80