apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app: pod-1
spec:
  containers:
  - name: pod-1-container
    image: nginx
    ports:
      - containerPort: 80
  nodeSelector:
    mylabel: mylabel

---

apiVersion: v1
kind: Service
metadata:
  name: pod-1-svc
spec:
  selector:
    app: pod-1
  type: NodePort 
  ports:
  - port: 80
