apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    app: pod-2
spec:
  nodeSelector:
    node: node1
  containers:
  - name: pod-2-container
    image: nginx
    ports:
      - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: pod-2-service
spec:
  selector:
    app: pod-2
  ports:
  - port: 8989
    targetPort: 80