apiVersion: v1
kind: Pod
metadata:
  name: portal-noticias
  labels:
    app: portal-noticias

spec:
  nodeSelector:
    node: node1
  containers:
  - name: portal-noticias-container
    image: aluracursos/portal-noticias:1
    ports:
      - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: portal-noticias-svc
spec:
  selector:
    app: portal-noticias
  type: NodePort
  ports:
  - port: 80
    nodePort: 30010
