/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.stdioh.javadb;

import br.com.stdioh.javadb.dao.ProdutoDao;
import br.com.stdioh.javadb.model.Produto;
import br.com.stdioh.javadb.utils.Utils;
import org.apache.commons.text.CharacterPredicates;
import org.apache.commons.text.RandomStringGenerator;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        try {

            ConexaoFactory conexaoFactory = new ConexaoFactory();

            for(int i =0; i < 20; i++){
                conexaoFactory.getConnection();
                System.out.println("Conexao: " + i);
            }

            ProdutoDao produtoDao = new ProdutoDao();

            var p = new Produto(Utils.getInstance().getRandomString(5));
            p.setDescricao(Utils.getInstance().getRandomString(12));
            produtoDao.add(p);
            produtoDao.findAll().forEach(produto -> {
                System.out.println(produto.getId() + ": " + produto.getNome() + " - " + produto.getDescricao());
            });


//            Properties prop = new Properties();
//            prop.load(App.class.getResourceAsStream("/application.properties"));
//            System.out.println(prop.getProperty("test"));
//            var conn = ConexaoFactory.getConnection();
//            var stmt = conn.createStatement();
//            var result = stmt.executeQuery("SELECT * FROM produto");
//            while (result.next()) {
//                int id = result.getInt("id");
//                String nome = result.getString("nome");
//                String desc = result.getString("descricao");
//                System.out.println(String.format("%d - %s, %s", id, nome, desc));
//            }
//            conn.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }
}
