/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.stdioh.testes;

import br.com.stdioh.testes.model.User;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        var mySystem = new MySystem();

        mySystem.addUser(User.builder().name("John").email("john@gmail.com").build());
        mySystem.addUser(User.builder().name("Mary").email("mary@gmail.com").build());
        mySystem.addUser(User.builder().name("Gary").email("gary@gmail.com").build());

        mySystem.getUsers().forEach(user -> {
            System.out.println(user);
        });

    }
}
